### ISSUE TITLE
Не работает метод send_search_by_keyword_request

### ISSUE THREAD

**Issue by Fan4Metal** [masterWeber/kinopoisk-api-unofficial-client#12]
Эндпоинт: /api/v2.1/films/search-by-keyword
Метод: send_search_by_keyword_request(request: SearchByKeywordRequest) -> SearchByKeywordResponse

Ошибки ValidationError. Пример с главной страницы не работает.

**Comment by Fan4Metal** [comment]
Похоже, проблема в модуле found_film.py, стр. 20: 

> year: Optional[int] = None

Но все равно многие поля пустые, самое главное - нет kinopoisk_id:

  request = SearchByKeywordRequest("Матрица")
  response = api_client.films.send_search_by_keyword_request(request)
  print(response.films[0])
  
  FoundFilm(kinopoisk_id=None, imdb_id=None, name_ru='Матрица', name_en='The Matrix', name_original=None, countries=[Country(country='Австралия'), Country(country='США')], genres=[Genre(genre='боевик'), Genre(genre='фантастика')], rating_kinopoisk=None, rating_imdb=None, type=<FilmType.FILM: 'FILM'>, film_length='02:16', poster_url='https://kinopoiskapiunofficial.tech/images/posters/kp/301.jpg', poster_url_preview='https://kinopoiskapiunofficial.tech/images/posters/kp_small/301.jpg')

**Comment by artanov** [comment]
починили ? не работает

**Comment by Fan4Metal** [comment]
> починили ? не работает

Если еще актуально, я поправил и сделал пул реквест.

**Comment by artanov** [comment]
Оо , спасибо ! :) 
Чекну

**Comment by artanov** [comment]
Добрый день ! 

В пятницу была доставка , пришел один нажимной механизм, я указывал, что два механизма вышли из строя , когда привезут второй ?

**Comment by masterWeber** [comment]
@artanov Это конечно интересно, но не ко мне вопрос.
