### ISSUE TITLE
bad requests

### ISSUE THREAD

**Issue by ksdafkkasgvdalbaeb** [masterWeber/kinopoisk-api-unofficial-client#13]
```
    request = FilmSearchByFiltersRequest()
    request.year_from = 1000
    request.rating_from = 0
    request.order = FilterOrder.RATING
    data = await state.get_data()
    ids = data.get("id")
    zanrsss = data.get("zanr")
    request.add_genre(FilterGenre(ids,zanrsss))
    request.add_country(FilterCountry(ids, coun)) 
    response = api_client.films.send_film_search_by_filters_request(request)
```

При попытке выполнить поиск фильма с фильтрами выдает bad requests. Случается это только во второй раз (т.е первый раз бот ищет фильм, на второй выдает ошибку, после перезапуска опять в первый раз работает, а во второй уже нет)

**Comment by masterWeber** [comment]
@ksdafkkasgvdalbaeb Не могу повторить проблему, можно полный пример? (без state.get_data())
