### ISSUE TITLE
A request.

### ISSUE THREAD

**Issue by stephen-iv** [masterWeber/kinopoisk-api-unofficial-client#18]
Hi! I didn't manage to find your contacts anywhere, so I only can write there. I can delete this issue later.
I am a sociology student, writing a graduate diploma thesis about cinema. I own statistical packages and plan to collect data from the sites kinopoisk, IMDb, rotten tomatoes, make descriptive statistics on them, twist a little data on python, build networks and conduct network analysis in R and Pajek. Parsing a kinopoisk is very difficult, but you know it yourself. Could you provide a csv copy of the database of films and actors of kinopoisk? I will be immensely grateful to you.... Maybe you have a sparse database of users and their reviews, ratings?
thank you in advance.
 
_All the best,
Stepan._
_svivanov_3@edu.hse.ru_

**Comment by masterWeber** [comment]
@stephen-iv Hi! Unfortunately, I don't have such a database, it's just a client for the [API](https://kinopoiskapiunofficial.tech/).

**Comment by stephen-iv** [comment]
Oh, Thank you anyway. Do you think it's possible to get whole database from
this api within 500 available requests or 1 request is equal to 1 film in
output?

**Comment by masterWeber** [comment]
@stephen-iv I think you can, but it will take some time.
