### ISSUE TITLE
Ошибка идентификационных номеров в запросе FiltersRequest

### ISSUE THREAD

**Issue by brawler2011** [masterWeber/kinopoisk-api-unofficial-client#19]
Здравствуйте!
Пользовался библиотекой kinopoisk_unofficial (python) и столкнулся с такой проблемой: при отправке запроса FiltersRequest, получаю соответствующий ответ, но при попытке отправить запрос FilmSearchByFiltersRequest c несколькими фильтрами из FiltersRequest, получаю неправильный ответ. Например, при request.countries = [FilterCountry(9, "Япония")] видно, что вместо Японии была найдена Германия. Можно сделать вывод, что запрос FiltersRequest возвращает неправильный ответ (id неправильные).
Прошу пояснить поведение FiltersRequest.
Пример кода прикреплен в файле test.py.
```
from kinopoisk_unofficial.request.films.filters_request import FiltersRequest
from kinopoisk_unofficial.request.films.film_search_by_filters_request import FilmSearchByFiltersRequest
from pprint import pprint

from api_client.api_client import api_client

req = FiltersRequest()
res = api_client.films.send_filters_request(req)
req = FilmSearchByFiltersRequest()
request = FilmSearchByFiltersRequest()
for item in res.countries:
    if item.country == "Япония":
        request.countries = [item]
        response = api_client.films.send_film_search_by_filters_request(request)
        print(item)
        pprint(response)
        break
```
# Т.е., вместо фильтра Япония был применён фильтр Германия
# Также обнаружил аналогичное неправильное поведение с фильтрами жанров

**Comment by brawler2011** [comment]
поменял PATH с v2.1 на v.2.2 и заработало

**Comment by masterWeber** [comment]
> поменял PATH с v2.1 на v.2.2 и заработало

Буду рад пулреквесту
