### ISSUE TITLE
Ошибка, когда встречаются пустые поля в карточке фильма

### ISSUE THREAD

**Issue by Fan4Metal** [masterWeber/kinopoisk-api-unofficial-client#7]
Добрый день!
В энтпоинте /api/v2.2/films/{id} когда когда в карточке фильма встречаются пустые поля, метод send_film_request вылетает.
Например:

1. 1103803: imdbId = null, ошибка
`apischema.validation.errors.ValidationError: ValidationError(messages=[], children={'imdbId': ValidationError(messages=['expected type string, found null'], children={})})`

2.  41519: nameOriginal =  null, ошибка
`apischema.validation.errors.ValidationError: ValidationError(messages=[], children={'nameOriginal': ValidationError(messages= 
    ['expected type string, found null'], children={})})`

**Comment by Fan4Metal** [comment]
Еще пример: 1283344, ratingGoodReview = null.

**Comment by masterWeber** [comment]
Спасибо, исправил. Если есть замечания или предложения, буду рад принять [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).
