### ISSUE TITLE
Ломается client при добавлении нового поля в api

### ISSUE THREAD

**Issue by TrueDevProfile** [masterWeber/kinopoisk-api-unofficial-client#9]
Добрый день. Похоже на то, что когда добавляется новое поле в респонсе от api, ваша либа начинает выдавать ошибки.
Сейчас добавлено новое поле logoUrl, аналогично https://github.com/masterWeber/kinopoisk-api-unofficial-client/issues/5 
Если это так, немогли бы вы сделать так чтобы, когда появлялись новые поля в api они просто игнорились и ничего не ломалось?

**Comment by masterWeber** [comment]
Спасибо, исправил. Если есть замечания или предложения, буду рад принять [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).
